# Generated by Django 4.1.3 on 2022-12-05 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': '会员类型', 'verbose_name_plural': '会员类型'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': '订阅记录', 'verbose_name_plural': '订阅记录'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'verbose_name': '会员用户', 'verbose_name_plural': '会员用户'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Annual', '年度会员'), ('Semi-annual', '半年会员'), ('Monthly', '月会员'), ('Free', 'free')], default='Free', max_length=30, verbose_name='会员类型'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.IntegerField(default=15, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_plan_id',
            field=models.CharField(max_length=40, verbose_name='Stripe Plan ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效期内'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=40, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.usermembership', verbose_name='会员用户'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership', verbose_name='会员类型'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='stripe_customer_id',
            field=models.CharField(max_length=40, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
