# Generated by Django 4.1.3 on 2022-12-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_easymath_id_subscription_easymath_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='easymath_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='easymath_id',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='easymath_id',
        ),
    ]
