# Generated by Django 4.1.3 on 2022-12-18 01:07

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=120, verbose_name="课程名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="课程描述"),
                ),
                (
                    "thumbnail",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="thumbnail"
                    ),
                ),
            ],
            options={"verbose_name": "系列课", "verbose_name_plural": "系列课",},
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=10, verbose_name="单元顺序")),
                ("title", models.CharField(max_length=120, verbose_name="单元名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="单元描述"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程单元",
                "verbose_name_plural": "课程单元",
                "ordering": ["course", "position"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=120, verbose_name="视频名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="视频描述"),
                ),
                ("position", models.IntegerField(default=10, verbose_name="视频顺序")),
                (
                    "video",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="video"
                    ),
                ),
                (
                    "video_additional",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="video_additional",
                    ),
                ),
                (
                    "thumbnail",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="thumbnail"
                    ),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="免费试看")),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.unit",
                        verbose_name="单元",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频",
                "verbose_name_plural": "视频",
                "ordering": ["course", "unit", "position"],
            },
        ),
        migrations.CreateModel(
            name="Exercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=10, verbose_name="习题顺序")),
                ("title", models.CharField(max_length=120, verbose_name="习题名称")),
                ("question", models.TextField(verbose_name="习题描述")),
                ("answer", models.CharField(max_length=120, verbose_name="答案")),
                (
                    "question_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="question_image",
                    ),
                ),
                (
                    "answer_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="answer_image",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.lesson",
                        verbose_name="所属视频",
                    ),
                ),
            ],
            options={"verbose_name": "习题", "verbose_name_plural": "习题",},
        ),
    ]
