# Generated by Django 4.1.3 on 2022-12-10 11:35

import cloudinary_storage.storage
import cloudinary_storage.validators
import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=courses.models.upload_location, validators=[cloudinary_storage.validators.validate_video], verbose_name='视频'),
        ),
    ]
