# Generated by Django 4.1.3 on 2022-12-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["course", "unit", "position"],
                "verbose_name": "视频",
                "verbose_name_plural": "视频",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "ordering": ["course", "position"],
                "verbose_name": "课程单元",
                "verbose_name_plural": "课程单元",
            },
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="所属课程",
            ),
        ),
    ]
