# Generated by Django 4.1.3 on 2022-12-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_exercises_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='answer',
            field=models.CharField(max_length=120, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='答案图片'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='所属视频'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='position',
            field=models.IntegerField(default=10, verbose_name='习题顺序'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='question',
            field=models.TextField(verbose_name='习题描述'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='习题图片'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='title',
            field=models.CharField(max_length=120, verbose_name='习题名称'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='免费试看'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(default=10, verbose_name='视频顺序'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.unit', verbose_name='单元'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频地址'),
        ),
    ]
