# Generated by Django 4.1.3 on 2022-12-16 11:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lesson_options_alter_unit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_additional",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video_additional"
            ),
        ),
    ]
