# Generated by Django 4.1.3 on 2023-02-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_exercises_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='课程缩略图文件名'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='课程缩略图文件名'),
        ),
    ]
