# Generated by Django 4.1.3 on 2022-12-10 11:49

import cloudinary_storage.storage
import cloudinary_storage.validators
import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_location, verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_location, verbose_name='答案图片'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_location, verbose_name='习题图片'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_location, verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=courses.models.upload_location, validators=[cloudinary_storage.validators.validate_video], verbose_name='视频'),
        ),
    ]
