# Generated by Django 4.1.3 on 2022-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='easymath_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EasyMathID'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='easymath_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EasyMathID'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='easymath_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EasyMathID'),
        ),
        migrations.AddField(
            model_name='unit',
            name='easymath_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EasyMathID'),
        ),
    ]
