# Generated by Django 4.1.3 on 2022-12-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_easymath_id_exercises_easymath_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='所属课程'),
        ),
    ]
