# Generated by Django 4.1.3 on 2022-12-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_video_url_lesson_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '系列课', 'verbose_name_plural': '系列课'},
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='test', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='answer_image',
            field=models.FileField(blank=True, null=True, upload_to='test', verbose_name='答案图片'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='question_image',
            field=models.FileField(blank=True, null=True, upload_to='test', verbose_name='习题图片'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='test', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='test', verbose_name='视频'),
        ),
    ]
