# Generated by Django 4.1.3 on 2022-12-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_unit_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='easymath_id',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='easymath_id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='easymath_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='easymath_id',
        ),
    ]
