# Generated by Django 4.1.3 on 2022-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='easymath_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EasyMathID'),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='easymath_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EasyMathID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='easymath_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EasyMathID'),
        ),
    ]
